INTEREST_MAPPINGS = {
    "aprendizado de maquina": ("Tecnologia e Computação", "Programação e Software"),
    "codigo": ("Tecnologia e Computação", "Programação e Software"),
    "programacao": ("Tecnologia e Computação", "Programação e Software"),
    "codar": ("Tecnologia e Computação", "Programação e Software"),
    "python": ("Tecnologia e Computação", "Programação e Software"),
    "javascript": ("Tecnologia e Computação", "Programação e Software"),
    "java": ("Tecnologia e Computação", "Programação e Software"),
    "html": ("Tecnologia e Computação", "Programação e Software"),
    "css": ("Tecnologia e Computação", "Programação e Software"),
    "php": ("Tecnologia e Computação", "Programação e Software"),
    "dev": ("Tecnologia e Computação", "Programação e Software"),
    "algoritmo": ("Tecnologia e Computação", "Programação e Software"),
    "bug": ("Tecnologia e Computação", "Programação e Software"),
    "programar jogos": ("Tecnologia e Computação", "Programação e Software"),
    "criar site": ("Tecnologia e Computação", "Programação e Software"),
    "fazer aplicativos": ("Tecnologia e Computação", "Programação e Software"),
    "engenharia de software": ("Tecnologia e Computação", "Programação e Software"),
    "programacao web": ("Tecnologia e Computação", "Programação e Software"),
    "criar apps": ("Tecnologia e Computação", "Programação e Software"),
    "backend": ("Tecnologia e Computação", "Programação e Software"),
    "frontend": ("Tecnologia e Computação", "Programação e Software"),
    "banco de dados": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "sql": ("Tecnologia e Computação", "Programação e Software"),
    "inteligencia artificial": ("Tecnologia e Computação", "Programação e Software"),
    "machine learning": ("Tecnologia e Computação", "Programação e Software"),
    "aprender a programar": ("Tecnologia e Computação", "Programação e Software"),
    "codificacao de sites": ("Tecnologia e Computação", "Programação e Software"),
    "software": ("Tecnologia e Computação", "Programação e Software"),
    "linux": ("Tecnologia e Computação", "Programação e Software"),

    "montar pc": ("Tecnologia e Computação", "Computação/Robótica"),
    "hardware": ("Tecnologia e Computação", "Computação/Robótica"),
    "circuito": ("Tecnologia e Computação", "Computação/Robótica"),
    "resistencia eletrica": ("Tecnologia e Computação", "Computação/Robótica"),
    "soldar": ("Tecnologia e Computação", "Computação/Robótica"),
    "computador": ("Tecnologia e Computação", "Computação/Robótica"),
    "pc gamer": ("Tecnologia e Computação", "Computação/Robótica"),
    "montar computadores": ("Tecnologia e Computação", "Computação/Robótica"),
    "construir pcs": ("Tecnologia e Computação", "Computação/Robótica"),
    "manutencao de computadores": ("Tecnologia e Computação", "Computação/Robótica"),
    "consertar eletrônicos": ("Tecnologia e Computação", "Computação/Robótica"),
    "placa de video": ("Tecnologia e Computação", "Computação/Robótica"),
    "placa-mae": ("Tecnologia e Computação", "Computação/Robótica"),
    "processador": ("Tecnologia e Computação", "Computação/Robótica"),
    "memoria ram": ("Tecnologia e Computação", "Computação/Robótica"),
    "fonte de alimentacao": ("Tecnologia e Computação", "Computação/Robótica"),
    "ssd": ("Tecnologia e Computação", "Computação/Robótica"),
    "componentes de computador": ("Tecnologia e Computação", "Computação/Robótica"),
    "tecnico em informatica": ("Tecnologia e Computação", "Computação/Robótica"),
    "robotica": ("Tecnologia e Computação", "Computação/Robótica"),
    "robo": ("Tecnologia e Computação", "Computação/Robótica"),
    "automacao": ("Tecnologia e Computação", "Programação e Software"),
    "lego mindstorms": ("Tecnologia e Computação", "Computação/Robótica"),
    "impressora 3d": ("Tecnologia e Computação", "Computação/Robótica"),
    "drone": ("Tecnologia e Computação", "Computação/Robótica"),
    "mecatronica": ("Tecnologia e Computação", "Computação/Robótica"),
    "competicao robotica": ("Tecnologia e Computação", "Computação/Robótica"),
    "construir robos": ("Tecnologia e Computação", "Computação/Robótica"),
    "inteligencia artificial para robos": ("Tecnologia e Computação", "Programação e Software"),
    "montagem de robos": ("Tecnologia e Computação", "Computação/Robótica"),
    "braço robotico": ("Tecnologia e Computação", "Computação/Robótica"),
    "casa inteligente": ("Tecnologia e Computação", "Programação e Software"),
    "veiculos autonomos": ("Tecnologia e Computação", "Programação e Software"),
    "sensores": ("Tecnologia e Computação", "Computação/Robótica"),
    "atuadores": ("Tecnologia e Computação", "Computação/Robótica"),
    "seguidor de linha": ("Tecnologia e Computação", "Computação/Robótica"),
    "olimpiada de robotica": ("Tecnologia e Computação", "Computação/Robótica"),
    "automacao residencial": ("Tecnologia e Computação", "Programação e Software"),
    "videogame": ("Tecnologia e Computação", "Computação/Robótica"),
    "jogar games": ("Tecnologia e Computação", "Programação e Software"),
    "gamer": ("Tecnologia e Computação", "Programação e Software"),
    "playstation": ("Tecnologia e Computação", "Computação/Robótica"),
    "xbox": ("Tecnologia e Computação", "Computação/Robótica"),
    "nintendo": ("Tecnologia e Computação", "Computação/Robótica"),
    "switch": ("Tecnologia e Computação", "Computação/Robótica"),
    "minecraft": ("Tecnologia e Computação", "Programação e Software"),
    "redstone": ("Tecnologia e Computação", "Programação e Software"),
    "fortnite": ("Tecnologia e Computação", "Programação e Software"),
    "lol": ("Tecnologia e Computação", "Programação e Software"),
    "cs": ("Tecnologia e Computação", "Programação e Software"),
    "counter-strike": ("Tecnologia e Computação", "Programação e Software"),
    "valorant": ("Tecnologia e Computação", "Programação e Software"),
    "twitch": ("Tecnologia e Computação", "Programação e Software"),
    "streamer": ("Tecnologia e Computação", "Programação e Software"),
    "jogos online": ("Tecnologia e Computação", "Programação e Software"),
    "campeonatos de games": ("Tecnologia e Computação", "Programação e Software"),
    "pro player": ("Tecnologia e Computação", "Programação e Software"),
    "cultura gamer": ("Tecnologia e Computação", "Programação e Software"),
    "jogos de computador": ("Tecnologia e Computação", "Programação e Software"),
    "steam": ("Tecnologia e Computação", "Programação e Software"),
    "design digital": ("Artes e Cultura", "Design Gráfico"),
    "illustrator": ("Artes e Cultura", "Design Gráfico"),
    "desenho digital": ("Artes e Cultura", "Design Gráfico"),
    "arte digital": ("Artes e Cultura", "Design Gráfico"),
    "modelagem 3d": ("Artes e Cultura", "Design Gráfico"),
    "blender": ("Artes e Cultura", "Design Gráfico"),
    "maya": ("Artes e Cultura", "Design Gráfico"),
    "edicao de video": ("Artes e Cultura", "Design Gráfico"),
    "after effects": ("Artes e Cultura", "Design Gráfico"),
    "design grafico": ("Artes e Cultura", "Design Gráfico"),
    "design de interfaces": ("Artes e Cultura", "Design Gráfico"),
    "ux design": ("Artes e Cultura", "Design Gráfico"),
    "ui design": ("Artes e Cultura", "Design Gráfico"),
    "editar fotos": ("Artes e Cultura", "Design Gráfico"),
    "criacao digital": ("Artes e Cultura", "Design Gráfico"),
    "logotipos": ("Artes e Cultura", "Design Gráfico"),
    "ilustracao digital": ("Artes e Cultura", "Design Gráfico"),
    "design para redes sociais": ("Artes e Cultura", "Design Gráfico"),
    "edicao de imagens": ("Artes e Cultura", "Design Gráfico"),
    "matematica": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "calculo": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "equacoes": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "algebra": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "geometria": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "olimpiada matematica": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "obmep": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "resolver problemas matematicos": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "trigonometria": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "estatistica": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "probabilidade": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "teorema de pitagoras": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "matematica financeira": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "raciocinio logico": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "numeros e formulas": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "desafios matematicos": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "cubo magico": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "sudoku": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "quebra-cabeca": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "jogos matematicos": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "simulações": ("Ciências Exatas", "Física"),
    "sistemas físicos": ("Ciências Exatas", "Física"),
    "fisica": ("Ciências Exatas", "Física"),
    "programação físicos": ("Ciências Exatas", "Física"),
    "mecanica": ("Ciências Exatas", "Física"),
    "eletricidade": ("Ciências Exatas", "Física"),
    "leis da fisica": ("Ciências Exatas", "Física"),
    "fisica quantica": ("Ciências Exatas", "Física"),
    "movimento": ("Ciências Exatas", "Física"),
    "energia": ("Ciências Exatas", "Física"),
    "relatividade": ("Ciências Exatas", "Física"),
    "gravitacao": ("Ciências Exatas", "Física"),
    "termodinamica": ("Ciências Exatas", "Física"),
    "optica": ("Ciências Exatas", "Física"),
    "ondas": ("Ciências Exatas", "Física"),
    "experimentos fisicos": ("Ciências Exatas", "Física"),
    "fisica experimental": ("Ciências Exatas", "Física"),
    "eletromagnetismo": ("Ciências Exatas", "Física"),
    "newton e suas leis": ("Ciências Exatas", "Física"),
    "forca e movimento": ("Ciências Exatas", "Física"),
    "experimentos de fisica": ("Ciências Exatas", "Física"),
    "problemas de fisica": ("Ciências Exatas", "Física"),
    "eclipse": ("Ciências Exatas", "Astronomia"),
    "chuva": ("Ciências Exatas", "Astronomia"),
    "meteoro": ("Ciências Exatas", "Astronomia"),
    "astronomia": ("Ciências Exatas", "Astronomia"),
    "espaco": ("Ciências Exatas", "Astronomia"),
    "planetas": ("Ciências Exatas", "Astronomia"),
    "estrelas": ("Ciências Exatas", "Astronomia"),
    "galaxias": ("Ciências Exatas", "Astronomia"),
    "universo": ("Ciências Exatas", "Astronomia"),
    "sistema solar": ("Ciências Exatas", "Astronomia"),
    "telescopio": ("Ciências Exatas", "Astronomia"),
    "observacao astronomica": ("Ciências Exatas", "Astronomia"),
    "cosmos": ("Ciências Exatas", "Astronomia"),
    "nasa": ("Ciências Exatas", "Astronomia"),
    "buraco negro": ("Ciências Exatas", "Astronomia"),
    "exploracao espacial": ("Ciências Exatas", "Astronomia"),
    "astronautas": ("Ciências Exatas", "Astronomia"),
    "foguetes": ("Ciências Exatas", "Astronomia"),
    "via lactea": ("Ciências Exatas", "Astronomia"),
    "astrofisica": ("Ciências Exatas", "Astronomia"),
    "observar ceu": ("Ciências Exatas", "Astronomia"),
    "mapa estelar": ("Ciências Exatas", "Astronomia"),
    "lua e suas fases": ("Ciências Exatas", "Astronomia"),

    # --- Química ---
    "quimica": ("Ciências Exatas", "Química"),
    "tabela periodica": ("Ciências Exatas", "Química"),
    "elementos quimicos": ("Ciências Exatas", "Química"),
    "reacoes quimicas": ("Ciências Exatas", "Química"),
    "quimica organica": ("Ciências Exatas", "Química"),
    "quimica inorganica": ("Ciências Exatas", "Química"),
    "compostos": ("Ciências Exatas", "Química"),
    "mistura": ("Ciências Exatas", "Química"),
    "acidos e bases": ("Ciências Exatas", "Química"),
    "experimentos quimicos": ("Ciências Exatas", "Química"),
    "laboratorio de quimica": ("Ciências Exatas", "Química"),
    "fazer experiencias": ("Ciências Exatas", "Química"),
    "slime": ("Ciências Exatas", "Química"),
    "vulcao de bicarbonato": ("Ciências Exatas", "Química"),
    "cristalizacao": ("Ciências Exatas", "Química"),
    "transformacoes quimicas": ("Ciências Exatas", "Química"),
    "olimpiada de quimica": ("Ciências Exatas", "Química"),
    "quimica na cozinha": ("Ciências Exatas", "Química"),
    "analise quimica": ("Ciências Exatas", "Química"),

    # --- Engenharia ---
    "engenharia": ("Ciências Exatas", "Engenharia"),
    "construcao": ("Ciências Exatas", "Engenharia"),
    "estruturas": ("Ciências Exatas", "Engenharia"),
    "maquete": ("Ciências Exatas", "Engenharia"),
    "desenho tecnico": ("Ciências Exatas", "Engenharia"),
    "pontes": ("Ciências Exatas", "Engenharia"),
    "engenharia civil": ("Ciências Exatas", "Engenharia"),
    "engenharia mecanica": ("Ciências Exatas", "Engenharia"),
    "engenharia eletrica": ("Ciências Exatas", "Engenharia"),
    "casas": ("Ciências Exatas", "Engenharia"),
    "construir edificios": ("Ciências Exatas", "Engenharia"),
    "projetar estruturas": ("Ciências Exatas", "Engenharia"),
    "infraestrutura": ("Ciências Exatas", "Engenharia"),
    "lego technic": ("Ciências Exatas", "Engenharia"),
    "projetar carros": ("Ciências Exatas", "Engenharia"),
    "redstone minecraft": ("Ciências Exatas", "Engenharia"),
    "circuitos de redstone": ("Ciências Exatas", "Engenharia"),
    "construcoes no minecraft": ("Ciências Exatas", "Engenharia"),
    "estudo dos organismos": ("Ciências Biológicas e Saúde", "Biologia"),
    "biologica celular": ("Ciências Biológicas e Saúde", "Biologia"),
    "classificacao de especies": ("Ciências Biológicas e Saúde", "Biologia"),
    "sistema nervoso": ("Ciências Biológicas e Saúde", "Biologia"),
    "sistema cardiovascular": ("Ciências Biológicas e Saúde", "Biologia"),
    "experimentos biologicos": ("Ciências Biológicas e Saúde", "Biologia"),
    "biologia": ("Ciências Biológicas e Saúde", "Biologia"),
    "seres vivos": ("Ciências Biológicas e Saúde", "Biologia"),
    "celulas": ("Ciências Biológicas e Saúde", "Biologia"),
    "genetica": ("Ciências Biológicas e Saúde", "Biologia"),
    "dna": ("Ciências Biológicas e Saúde", "Biologia"),
    "evolucao": ("Ciências Biológicas e Saúde", "Biologia"),
    "darwin": ("Ciências Biológicas e Saúde", "Biologia"),
    "selecao natural": ("Ciências Biológicas e Saúde", "Biologia"),
    "biologo": ("Ciências Biológicas e Saúde", "Biologia"),
    "professor biologia": ("Ciências Biológicas e Saúde", "Biologia"),
    "gostar biologia": ("Ciências Biológicas e Saúde", "Biologia"),
    "microscopio": ("Ciências Biológicas e Saúde", "Biologia"),
    "observar microscopio": ("Ciências Biológicas e Saúde", "Biologia"),
    "biotecnologia": ("Ciências Biológicas e Saúde", "Biologia"),
    "biodiversidade": ("Ciências Biológicas e Saúde", "Biologia"),
    "estudo biodiversidade": ("Ciências Biológicas e Saúde", "Biologia"),
    "estudar biodiversidade": ("Ciências Biológicas e Saúde", "Biologia"),
    "grupos estudo biodiversidade": ("Ciências Biológicas e Saúde", "Biologia"),
    "biologia molecular": ("Ciências Biológicas e Saúde", "Biologia"),
    "microbiologia": ("Ciências Biológicas e Saúde", "Biologia"),
    "taxonomia": ("Ciências Biológicas e Saúde", "Biologia"),
    "classificacao especies": ("Ciências Biológicas e Saúde", "Biologia"),
    "parasitologia": ("Ciências Biológicas e Saúde", "Biologia"),
    "biologia marinha": ("Ciências Biológicas e Saúde", "Biologia"),
    "aquario": ("Ciências Biológicas e Saúde", "Biologia"),
    "peixes": ("Ciências Biológicas e Saúde", "Biologia"),
    "aquarismo": ("Ciências Biológicas e Saúde", "Biologia"),
    "terrario": ("Ciências Biológicas e Saúde", "Biologia"),
    "olimpiada biologia": ("Ciências Biológicas e Saúde", "Biologia"),
    "obb": ("Ciências Biológicas e Saúde", "Biologia"),
    "area saude": ("Ciências Biológicas e Saúde", "Medicina"),
    "cuidar pessoas": ("Ciências Biológicas e Saúde", "Medicina"),
    "ajudar doentes": ("Ciências Biológicas e Saúde", "Medicina"),
    "salvar vidas": ("Ciências Biológicas e Saúde", "Medicina"),
    "trabalhar hospital": ("Ciências Biológicas e Saúde", "Medicina"),
    "jogos operar": ("Ciências Biológicas e Saúde", "Medicina"),
    "surgeon simulator": ("Ciências Biológicas e Saúde", "Medicina"),
    "curativos": ("Ciências Biológicas e Saúde", "Medicina"),
    "remedios": ("Ciências Biológicas e Saúde", "Medicina"),
    "medicina": ("Ciências Biológicas e Saúde", "Medicina"),
    "medico": ("Ciências Biológicas e Saúde", "Medicina"),
    "enfermagem": ("Ciências Biológicas e Saúde", "Medicina"),
    "odontologia": ("Ciências Biológicas e Saúde", "Medicina"),
    "farmacia": ("Ciências Biológicas e Saúde", "Medicina"),
    "anatomia": ("Ciências Biológicas e Saúde", "Medicina"),
    "fisioterapia": ("Ciências Biológicas e Saúde", "Medicina"),
    "corpo humano": ("Ciências Biológicas e Saúde", "Medicina"),
    "doencas": ("Ciências Biológicas e Saúde", "Medicina"),
    "tratamentos": ("Ciências Biológicas e Saúde", "Medicina"),
    "cirurgia": ("Ciências Biológicas e Saúde", "Medicina"),
    "primeiros socorros": ("Ciências Biológicas e Saúde", "Medicina"),
    "fisiologia humana": ("Ciências Biológicas e Saúde", "Medicina"),
    "saude": ("Ciências Biológicas e Saúde", "Medicina"),
    "pacientes": ("Ciências Biológicas e Saúde", "Medicina"),
    "hospital": ("Ciências Biológicas e Saúde", "Medicina"),
    "curativo": ("Ciências Biológicas e Saúde", "Medicina"),
    "emergencias medicas": ("Ciências Biológicas e Saúde", "Medicina"),
    "biomedicina": ("Ciências Biológicas e Saúde", "Medicina"),
    "clinica medica": ("Ciências Biológicas e Saúde", "Medicina"),
    "medicina veterinaria": ("Ciências Biológicas e Saúde", "Veterinária"),

    "cuidar animais": ("Ciências Biológicas e Saúde", "Veterinária"),
    "trabalhar com animais": ("Ciências Biológicas e Saúde", "Veterinária"),
    "gostar animais": ("Ciências Biológicas e Saúde", "Veterinária"),
    "cachorros": ("Ciências Biológicas e Saúde", "Veterinária"),
    "cavalo": ("Ciências Biológicas e Saúde", "Veterinária"),
    "pet shop": ("Ciências Biológicas e Saúde", "Veterinária"),
    "pet": ("Ciências Biológicas e Saúde", "Veterinária"),
    "animal simulator": ("Ciências Biológicas e Saúde", "Veterinária"),
    "animal crossing": ("Ciências Biológicas e Saúde", "Veterinária"),
    "zoologico": ("Ciências Biológicas e Saúde", "Veterinária"),
    "adestrar": ("Ciências Biológicas e Saúde", "Veterinária"),
    "adestramento": ("Ciências Biológicas e Saúde", "Veterinária"),

    # --- Veterinária ---
    "veterinaria": ("Ciências Biológicas e Saúde", "Veterinária"),
    "animais": ("Ciências Biológicas e Saúde", "Veterinária"),
    "cuidar de animais": ("Ciências Biológicas e Saúde", "Veterinária"),
    "pets": ("Ciências Biológicas e Saúde", "Veterinária"),
    "saude animal": ("Ciências Biológicas e Saúde", "Veterinária"),
    "clinica veterinaria": ("Ciências Biológicas e Saúde", "Veterinária"),
    "veterinario": ("Ciências Biológicas e Saúde", "Veterinária"),
    "tratamento animal": ("Ciências Biológicas e Saúde", "Veterinária"),
    "caes": ("Ciências Biológicas e Saúde", "Veterinária"),
    "gatos": ("Ciências Biológicas e Saúde", "Veterinária"),
    "medicina animal": ("Ciências Biológicas e Saúde", "Veterinária"),
    "cirurgia animal": ("Ciências Biológicas e Saúde", "Veterinária"),
    "zoologia": ("Ciências Biológicas e Saúde", "Veterinária"),
    "fauna": ("Ciências Biológicas e Saúde", "Veterinária"),
    "zoo": ("Ciências Biológicas e Saúde", "Veterinária"),
    "animais selvagens": ("Ciências Biológicas e Saúde", "Veterinária"),
    "comportamento animal": ("Ciências Biológicas e Saúde", "Veterinária"),
    "vacinas animais": ("Ciências Biológicas e Saúde", "Veterinária"),
    "fisiologia animal": ("Ciências Biológicas e Saúde", "Veterinária"),
    "anatomia animal": ("Ciências Biológicas e Saúde", "Veterinária"),
    # --- Ecologia e Meio Ambiente ---
    "ecologia": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "poluição": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "poluição em áreas urbanas": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "qualidade da água": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "ecossistemas": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "interações entre espécies": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "meio ambiente": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "natureza": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "sustentabilidade": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "reciclagem": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "reciclar": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "planeta": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "salvar planeta": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "aquecimento global": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "mudancas climaticas": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "animais em extincao": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "estudar animais": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "floresta": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "amazonia": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "plantas": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "plantar": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "jardim": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "cuidar plantas": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "cultivo": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "horta": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "energia renovavel": ("Ciências Exatas", "Engenharia"),
    "energia limpa": ("Ciências Exatas", "Engenharia"),
    "poluicao": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "ambientalista": ("Ciências Biológicas e Saúde", "Ecologia e Meio Ambiente"),
    "ajudar pessoas": ("Ciências Biológicas e Saúde", "Psicologia"),
    "estudar saude mental": ("Ciências Biológicas e Saúde", "Psicologia"),
    "grupos estudo saude mental": ("Ciências Biológicas e Saúde", "Psicologia"),
    "entender pessoas": ("Ciências Biológicas e Saúde", "Psicologia"),
    "entender comportamento": ("Ciências Biológicas e Saúde", "Psicologia"),
    "conflitos emocionais": ("Ciências Biológicas e Saúde", "Psicologia"),
    "escutar pessoas": ("Ciências Biológicas e Saúde", "Psicologia"),
    "ansiedade": ("Ciências Biológicas e Saúde", "Psicologia"),
    "depressao": ("Ciências Biológicas e Saúde", "Psicologia"),
    "transtornos": ("Ciências Biológicas e Saúde", "Psicologia"),
    "testes personalidade": ("Ciências Biológicas e Saúde", "Psicologia"),
    "mbti": ("Ciências Biológicas e Saúde", "Psicologia"),
    # --- Saúde e Bem-estar ---
    "nutricao": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "alimentacao saudavel": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "exercicios fisicos": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "dieta": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "qualidade de vida": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "habitos saudaveis": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "yoga": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "pilates": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "bem estar": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "nutricionista": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "treinamento funcional": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "meditacao": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "saude mental": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "equilibrio vida": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "suplementacao": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "calistenia": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    "metabolismo": ("Ciências Biológicas e Saúde", "Saúde e Bem-estar"),
    # --- Artes Visuais ---
    "desenhar": ("Artes e Cultura", "Artes Visuais"),
    "pintar": ("Artes e Cultura", "Artes Visuais"),
    "arte": ("Artes e Cultura", "Artes Visuais"),
    "artista": ("Artes e Cultura", "Artes Visuais"),
    "ilustrar": ("Artes e Cultura", "Artes Visuais"),
    "hq": ("Artes e Cultura", "Artes Visuais"),
    "character design": ("Artes e Cultura", "Artes Visuais"),
    "criar personagens": ("Artes e Cultura", "Artes Visuais"),
    "mangaka": ("Artes e Cultura", "Artes Visuais"),
    "modelar": ("Artes e Cultura", "Artes Visuais"),
    "argila": ("Artes e Cultura", "Artes Visuais"),
    "biscuit": ("Artes e Cultura", "Artes Visuais"),
    "artesanato": ("Artes e Cultura", "Artes Visuais"),
    "fazer croche": ("Artes e Cultura", "Artes Visuais"),
    "fazer tricot": ("Artes e Cultura", "Artes Visuais"),
    "costurar": ("Artes e Cultura", "Artes Visuais"),
    "digital art": ("Artes e Cultura", "Artes Visuais"),
    "procreate": ("Artes e Cultura", "Artes Visuais"),
    "pintura digital": ("Artes e Cultura", "Artes Visuais"),
    "draw with me": ("Artes e Cultura", "Artes Visuais"),
    "desenho": ("Artes e Cultura", "Artes Visuais"),
    "pintura": ("Artes e Cultura", "Artes Visuais"),
    "escultura": ("Artes e Cultura", "Artes Visuais"),
    "manga": ("Artes e Cultura", "Artes Visuais"),
    "anime": ("Artes e Cultura", "Artes Visuais"),
    "quadrinhos": ("Artes e Cultura", "Artes Visuais"),
    "artes plasticas": ("Artes e Cultura", "Artes Visuais"),
    "ilustracao": ("Artes e Cultura", "Artes Visuais"),
    "aquarela": ("Artes e Cultura", "Artes Visuais"),
    "desenhar personagens": ("Artes e Cultura", "Artes Visuais"),
    "desenho realista": ("Artes e Cultura", "Artes Visuais"),
    "chibi": ("Artes e Cultura", "Artes Visuais"),
    "criar arte": ("Artes e Cultura", "Artes Visuais"),
    "tecnica de desenho": ("Artes e Cultura", "Artes Visuais"),
    "fanart": ("Artes e Cultura", "Artes Visuais"),
    "retrato": ("Artes e Cultura", "Artes Visuais"),
    "artista plastico": ("Artes e Cultura", "Artes Visuais"),
    "lapis de cor": ("Artes e Cultura", "Artes Visuais"),
    "sketches": ("Artes e Cultura", "Artes Visuais"),
    "marcadores": ("Artes e Cultura", "Artes Visuais"),
    "camera": ("Artes e Cultura", "Fotografia"),
    "fotos": ("Artes e Cultura", "Fotografia"),
    "composicao fotografica": ("Artes e Cultura", "Fotografia"),
    "edicao fotos": ("Artes e Cultura", "Fotografia"),
    "photoshop": ("Artes e Cultura", "Fotografia"),
    "filtros": ("Artes e Cultura", "Fotografia"),
    "fotografia natureza": ("Artes e Cultura", "Fotografia"),
    "fotografia retrato": ("Artes e Cultura", "Fotografia"),
    "fotografia paisagem": ("Artes e Cultura", "Fotografia"),
    "fotografia urbana": ("Artes e Cultura", "Fotografia"),
    # --- Fotografia ---
    "fotografia": ("Artes e Cultura", "Fotografia"),
    "fotografar": ("Artes e Cultura", "Fotografia"),
    "tirar fotos": ("Artes e Cultura", "Fotografia"),
    "camera fotografica": ("Artes e Cultura", "Fotografia"),
    "dslr": ("Artes e Cultura", "Fotografia"),
    "lentes": ("Artes e Cultura", "Fotografia"),
    "iluminacao": ("Artes e Cultura", "Fotografia"),
    "composicao": ("Artes e Cultura", "Fotografia"),
    "fotografia de paisagem": ("Artes e Cultura", "Fotografia"),
    "fotografia de retrato": ("Artes e Cultura", "Fotografia"),
    "ensaio fotografico": ("Artes e Cultura", "Fotografia"),
    "fotojornalismo": ("Artes e Cultura", "Fotografia"),
    "fotografia street": ("Artes e Cultura", "Fotografia"),
    "instagram": ("Artes e Cultura", "Fotografia"),
    "post": ("Artes e Cultura", "Fotografia"),
    "edicao de fotos": ("Artes e Cultura", "Fotografia"),
    "lightroom": ("Artes e Cultura", "Fotografia"),
    "fotografia de natureza": ("Artes e Cultura", "Fotografia"),
    "book": ("Artes e Cultura", "Fotografia"),
    # --- Música ---
    "musica": ("Artes e Cultura", "Música"),
    "cantar": ("Artes e Cultura", "Música"),
    "canto": ("Artes e Cultura", "Música"),
    "tocar instrumento": ("Artes e Cultura", "Música"),
    "tocar violao": ("Artes e Cultura", "Música"),
    "tocar guitarra": ("Artes e Cultura", "Música"),
    "tocar piano": ("Artes e Cultura", "Música"),
    "tocar teclado": ("Artes e Cultura", "Música"),
    "tocar bateria": ("Artes e Cultura", "Música"),
    "tocar baixo": ("Artes e Cultura", "Música"),
    "tocar ukulele": ("Artes e Cultura", "Música"),
    "compor": ("Artes e Cultura", "Música"),
    "compor musicas": ("Artes e Cultura", "Música"),
    "escrever cancoes": ("Artes e Cultura", "Música"),
    "bandas": ("Artes e Cultura", "Música"),
    "fazer cover": ("Artes e Cultura", "Música"),
    "rock": ("Artes e Cultura", "Música"),
    "pop": ("Artes e Cultura", "Música"),
    "rap": ("Artes e Cultura", "Música"),
    "hip hop": ("Artes e Cultura", "Música"),
    "funk": ("Artes e Cultura", "Música"),
    "sertanejo": ("Artes e Cultura", "Música"),
    "pagode": ("Artes e Cultura", "Música"),
    "mpb": ("Artes e Cultura", "Música"),
    "jazz": ("Artes e Cultura", "Música"),
    "metal": ("Artes e Cultura", "Música"),
    "eletronica": ("Artes e Cultura", "Música"),
    "dj": ("Artes e Cultura", "Música"),
    "produzir beats": ("Artes e Cultura", "Música"),
    "produtor musical": ("Artes e Cultura", "Música"),
    "fl studio": ("Artes e Cultura", "Música"),
    "ableton": ("Artes e Cultura", "Música"),
    "logic pro": ("Artes e Cultura", "Música"),
    "garageband": ("Artes e Cultura", "Música"),
    "musica eletronica": ("Artes e Cultura", "Música"),
    "soundcloud": ("Artes e Cultura", "Música"),
    "spotify": ("Artes e Cultura", "Música"),
    "karaoke": ("Artes e Cultura", "Música"),
    "assistir filmes": ("Artes e Cultura", "Cinema e Audiovisual"),
    "maratonar series": ("Artes e Cultura", "Cinema e Audiovisual"),
    "netflix": ("Artes e Cultura", "Cinema e Audiovisual"),
    "disney plus": ("Artes e Cultura", "Cinema e Audiovisual"),
    "prime video": ("Artes e Cultura", "Cinema e Audiovisual"),
    "hbo": ("Artes e Cultura", "Cinema e Audiovisual"),
    "fazer filmes": ("Artes e Cultura", "Cinema e Audiovisual"),
    "escrever roteiros": ("Artes e Cultura", "Cinema e Audiovisual"),
    "curtametragem": ("Artes e Cultura", "Cinema e Audiovisual"),
    "filmagem": ("Artes e Cultura", "Cinema e Audiovisual"),
    "premiere": ("Artes e Cultura", "Cinema e Audiovisual"),
    "davinci resolve": ("Artes e Cultura", "Cinema e Audiovisual"),
    "fazer videos": ("Artes e Cultura", "Cinema e Audiovisual"),
    "canal youtube": ("Artes e Cultura", "Cinema e Audiovisual"),
    "criador conteudo": ("Artes e Cultura", "Cinema e Audiovisual"),
    "streaming": ("Artes e Cultura", "Cinema e Audiovisual"),
    "filmes animacao": ("Artes e Cultura", "Cinema e Audiovisual"),
    "pixar": ("Artes e Cultura", "Cinema e Audiovisual"),
    "disney": ("Artes e Cultura", "Cinema e Audiovisual"),
    "dreamworks": ("Artes e Cultura", "Cinema e Audiovisual"),
    "stop motion": ("Artes e Cultura", "Cinema e Audiovisual"),
    "violao": ("Artes e Cultura", "Música"),
    "guitarra": ("Artes e Cultura", "Música"),
    "piano": ("Artes e Cultura", "Música"),
    "bateria": ("Artes e Cultura", "Música"),
    "banda": ("Artes e Cultura", "Música"),
    "teoria musical": ("Artes e Cultura", "Música"),
    "tocar por ouvido": ("Artes e Cultura", "Música"),
    "produzir musica": ("Artes e Cultura", "Música"),
    "mixagem": ("Artes e Cultura", "Música"),
    "cifras": ("Artes e Cultura", "Música"),
    "partitura": ("Artes e Cultura", "Música"),
    "baixo": ("Artes e Cultura", "Música"),
    "teclado": ("Artes e Cultura", "Música"),
    "musico": ("Artes e Cultura", "Música"),

    # --- Cinema e Audiovisual ---
    "cinema": ("Artes e Cultura", "Cinema e Audiovisual"),
    "filmes": ("Artes e Cultura", "Cinema e Audiovisual"),
    "filmar": ("Artes e Cultura", "Cinema e Audiovisual"),
    "producao de video": ("Artes e Cultura", "Cinema e Audiovisual"),
    "roteiro": ("Artes e Cultura", "Cinema e Audiovisual"),
    "direcao": ("Artes e Cultura", "Cinema e Audiovisual"),
    "editar videos": ("Artes e Cultura", "Cinema e Audiovisual"),
    "documentario": ("Artes e Cultura", "Cinema e Audiovisual"),
    "curta-metragem": ("Artes e Cultura", "Cinema e Audiovisual"),
    "youtube": ("Artes e Cultura", "Cinema e Audiovisual"),
    "youtuber": ("Artes e Cultura", "Cinema e Audiovisual"),
    "vlog": ("Artes e Cultura", "Cinema e Audiovisual"),
    "producao audiovisual": ("Artes e Cultura", "Cinema e Audiovisual"),
    "animacao": ("Artes e Cultura", "Cinema e Audiovisual"),
    "animador": ("Artes e Cultura", "Cinema e Audiovisual"),
    "series": ("Artes e Cultura", "Cinema e Audiovisual"),
    "efeitos especiais": ("Artes e Cultura", "Cinema e Audiovisual"),
    "videomaker": ("Artes e Cultura", "Cinema e Audiovisual"),
    "criador de conteudo": ("Artes e Cultura", "Cinema e Audiovisual"),
    "cinematografia": ("Artes e Cultura", "Cinema e Audiovisual"),
    "tiktok": ("Artes e Cultura", "Cinema e Audiovisual"),
    "ator": ("Artes e Cultura", "Teatro e Dança"),
    "atriz": ("Artes e Cultura", "Teatro e Dança"),
    "danca contemporanea": ("Artes e Cultura", "Teatro e Dança"),
    "k-pop dance": ("Artes e Cultura", "Teatro e Dança"),
    "break dance": ("Artes e Cultura", "Teatro e Dança"),
    "tiktok dance": ("Artes e Cultura", "Teatro e Dança"),
    "grupo danca": ("Artes e Cultura", "Teatro e Dança"),
    "grupo teatro": ("Artes e Cultura", "Teatro e Dança"),
    "musicais": ("Artes e Cultura", "Teatro e Dança"),
    "stand up": ("Artes e Cultura", "Teatro e Dança"),
    "comedia": ("Artes e Cultura", "Teatro e Dança"),
    "fazer humor": ("Artes e Cultura", "Teatro e Dança"),
    "palhaço": ("Artes e Cultura", "Teatro e Dança"),
    "circo": ("Artes e Cultura", "Teatro e Dança"),
    "teatro": ("Artes e Cultura", "Teatro e Dança"),
    "atuacao": ("Artes e Cultura", "Teatro e Dança"),
    "atuar": ("Artes e Cultura", "Teatro e Dança"),
    "palco": ("Artes e Cultura", "Teatro e Dança"),
    "peca teatral": ("Artes e Cultura", "Teatro e Dança"),
    "danca": ("Artes e Cultura", "Teatro e Dança"),
    "dancar": ("Artes e Cultura", "Teatro e Dança"),
    "ballet": ("Artes e Cultura", "Teatro e Dança"),
    "contemporaneo": ("Artes e Cultura", "Teatro e Dança"),
    "danca de rua": ("Artes e Cultura", "Teatro e Dança"),
    "hip hop dance": ("Artes e Cultura", "Teatro e Dança"),
    "street dance": ("Artes e Cultura", "Teatro e Dança"),
    "coreografia": ("Artes e Cultura", "Teatro e Dança"),
    "improvisacao": ("Artes e Cultura", "Teatro e Dança"),
    "performer": ("Artes e Cultura", "Teatro e Dança"),
    "stand-up": ("Artes e Cultura", "Teatro e Dança"),
    "musical": ("Artes e Cultura", "Teatro e Dança"),
    "grupo teatral": ("Artes e Cultura", "Teatro e Dança"),
    "dancarina": ("Artes e Cultura", "Teatro e Dança"),
    "coreografo": ("Artes e Cultura", "Teatro e Dança"),

    "poema": ("Literatura e Linguagem", "Literatura"),
    "escrita criativa": ("Literatura e Linguagem", "Literatura"),
    "criar historias": ("Literatura e Linguagem", "Literatura"),
    "narrativas": ("Literatura e Linguagem", "Literatura"),
    "literatura": ("Literatura e Linguagem", "Literatura"),
    "ficcao": ("Literatura e Linguagem", "Literatura"),
    "historias": ("Literatura e Linguagem", "Literatura"),
    "autor": ("Literatura e Linguagem", "Literatura"),
    "sarau": ("Literatura e Linguagem", "Literatura"),
    "slam": ("Literatura e Linguagem", "Literatura"),
    "clube do livro": ("Literatura e Linguagem", "Literatura"),
    "ler": ("Literatura e Linguagem", "Literatura"),
    "leitura": ("Literatura e Linguagem", "Literatura"),
    "livros": ("Literatura e Linguagem", "Literatura"),
    "escrever": ("Literatura e Linguagem", "Literatura"),
    "escrita": ("Literatura e Linguagem", "Literatura"),
    "escrever historias": ("Literatura e Linguagem", "Literatura"),
    "escritor": ("Literatura e Linguagem", "Literatura"),
    "wattpad": ("Literatura e Linguagem", "Literatura"),
    "fanfiction": ("Literatura e Linguagem", "Literatura"),
    "poesia": ("Literatura e Linguagem", "Literatura"),
    "poemas": ("Literatura e Linguagem", "Literatura"),
    "contos": ("Literatura e Linguagem", "Literatura"),
    "romance": ("Literatura e Linguagem", "Literatura"),
    "fantasia": ("Literatura e Linguagem", "Literatura"),
    "ficcao cientifica": ("Literatura e Linguagem", "Literatura"),
    "terror": ("Literatura e Linguagem", "Literatura"),
    "suspense": ("Literatura e Linguagem", "Literatura"),
    "harry potter": ("Literatura e Linguagem", "Literatura"),
    "percy jackson": ("Literatura e Linguagem", "Literatura"),
    "senhor dos aneis": ("Literatura e Linguagem", "Literatura"),
    "cronicas narnia": ("Literatura e Linguagem", "Literatura"),
    "diario": ("Literatura e Linguagem", "Literatura"),
    "escrever diario": ("Literatura e Linguagem", "Literatura"),
    "bullet journal": ("Literatura e Linguagem", "Literatura"),
    "club do livro": ("Literatura e Linguagem", "Literatura"),
    "goodreads": ("Literatura e Linguagem", "Literatura"),
    "skoob": ("Literatura e Linguagem", "Literatura"),
    "booktuber": ("Literatura e Linguagem", "Literatura"),
    "booktok": ("Literatura e Linguagem", "Literatura"),
    "bookstagram": ("Literatura e Linguagem", "Literatura"),
    # --- Idiomas e Linguística ---
    "idiomas": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "linguas": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "ingles": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "espanhol": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "frances": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "alemao": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "italiano": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "japones": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "coreano": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "mandarim": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "chines": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "linguistica": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "aprender lingua": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "traducao": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "gramatica": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "vocabulario": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "fluencia": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "intercambio": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "idioma estrangeiro": ("Literatura e Linguagem", "Idiomas e Linguística"),
    "portugues": ("Literatura e Linguagem", "Idiomas e Linguística"),

    "bicicleta": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "bike": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "mountain bike": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "tenis": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "jogar tenis": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "pratico tenis": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "torneios tenis": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "surf": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "surfar": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "skate": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "andar skate": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "skatista": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "patins": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "patinacao": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "patinar": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "ginastica": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "ginastica artistica": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "ginastica ritmica": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "parkour": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "escalada": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "escalar": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "golfe": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "triatlo": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "maratona": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "corrida rua": ("Esportes e Atividades Físicas", "Esportes Individuais"),

    "futebol": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "jogar futebol": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "jogar bola": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "fifa": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "futsal": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "society": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "volei": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "voleibol": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "basquete": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "basquetebol": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "nba": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "nba 2k": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "handebol": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "rugby": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "polo aquatico": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "time": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "torcedor": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "selecao brasileira": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "jogador": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "copa mundo": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "olimpiadas": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "campeonato": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "torneio": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "handball": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "jogador de futebol": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "jogo em equipe": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "hoquei": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "treinamento": ("Esportes e Atividades Físicas", "Esportes Coletivos"),
    "tatica de jogo": ("Esportes e Atividades Físicas", "Esportes Coletivos"),

    # --- Esportes Individuais ---
    "natacao": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "nadar": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "atletismo": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "corrida": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "correr": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "ciclismo": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "pedalar": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "ping pong": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "surfe": ("Esportes e Atividades Físicas", "Esportes Individuais"),
    "corredor": ("Esportes e Atividades Físicas", "Esportes Individuais"),

    # --- Artes Marciais ---
    "artes marciais": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "luta": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "judo": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "karate": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "taekwondo": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "jiu jitsu": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "bjj": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "muay thai": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "boxe": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "mma": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "ufc": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "capoeira": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "kung fu": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "defesa pessoal": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "academia de luta": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "faixa preta": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "kimono": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "tatame": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "dojo": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "aikido": ("Esportes e Atividades Físicas", "Artes Marciais"),
    # --- Artes Marciais ---
    "arte marcial": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "lutar": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "academia luta": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "faixa": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "mortal kombat": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "street fighter": ("Esportes e Atividades Físicas", "Artes Marciais"),
    "tekken": ("Esportes e Atividades Físicas", "Artes Marciais"),
    # --- Fitness ---
    "academia": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "musculacao": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "treino": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "exercicios": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "personal trainer": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "crossfit": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "hiit": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "funcional": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "malhar": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "condicionamento fisico": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "definicao muscular": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "treino de forca": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "fisiculturismo": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "bodybuilding": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "perder peso": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "ganhar massa": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "levantamento de peso": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "suplementacao esportiva": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "preparacao fisica": ('Ciências Biológicas e Saúde', 'Saúde e Bem-estar'),
    "historia": ("Ciências Humanas e Sociais", "História"),
    "historiador": ("Ciências Humanas e Sociais", "História"),
    "passado": ("Ciências Humanas e Sociais", "História"),
    "civilizacoes": ("Ciências Humanas e Sociais", "História"),
    "antiguidade": ("Ciências Humanas e Sociais", "História"),
    "era moderna": ("Ciências Humanas e Sociais", "História"),
    "contemporanea": ("Ciências Humanas e Sociais", "História"),
    "descobrimentos": ("Ciências Humanas e Sociais", "História"),
    "revolucao": ("Ciências Humanas e Sociais", "História"),
    "fatos historicos": ("Ciências Humanas e Sociais", "História"),
    "personagens historicos": ("Ciências Humanas e Sociais", "História"),
    "historia mundial": ("Ciências Humanas e Sociais", "História"),
    "periodo historico": ("Ciências Humanas e Sociais", "História"),
    "estudar historia": ("Ciências Humanas e Sociais", "História"),
    "museu historico": ("Ciências Humanas e Sociais", "História"),
    "historia antiga": ("Ciências Humanas e Sociais", "História"),
    "egipcios": ("Ciências Humanas e Sociais", "História"),
    "grecia antiga": ("Ciências Humanas e Sociais", "História"),
    "roma antiga": ("Ciências Humanas e Sociais", "História"),
    "idade media": ("Ciências Humanas e Sociais", "História"),
    "medieval": ("Ciências Humanas e Sociais", "História"),
    "castelos": ("Ciências Humanas e Sociais", "História"),
    "cavaleiros": ("Ciências Humanas e Sociais", "História"),
    "renascimento": ("Ciências Humanas e Sociais", "História"),
    "revolucao francesa": ("Ciências Humanas e Sociais", "História"),
    "revolucao industrial": ("Ciências Humanas e Sociais", "História"),
    "guerras mundiais": ("Ciências Humanas e Sociais", "História"),
    "guerra fria": ("Ciências Humanas e Sociais", "História"),
    "historia do brasil": ("Ciências Humanas e Sociais", "História"),
    "arqueologia": ("Ciências Humanas e Sociais", "História"),
    "museus": ("Ciências Humanas e Sociais", "História"),
    "visitar museus": ("Ciências Humanas e Sociais", "História"),
    "discovery channel": ("Ciências Humanas e Sociais", "História"),
    "history channel": ("Ciências Humanas e Sociais", "História"),
    "documentarios historicos": ("Ciências Humanas e Sociais", "História"),
    "games historicos": ("Ciências Humanas e Sociais", "História"),
    "assassins creed": ("Ciências Humanas e Sociais", "História"),
    "age of empires": ("Ciências Humanas e Sociais", "História"),
    "civilization": ("Ciências Humanas e Sociais", "História"),
    "total war": ("Ciências Humanas e Sociais", "História"),

    # --- Filosofia e Ética ---
    "filosofia": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "filosofo": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "pensamento": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "reflexao": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "questionamento": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "etica": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "moral": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "existencialismo": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "conhecimento": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "logica filosofica": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "socrates": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "aristoteles": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "platao": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "nietzsche": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "filosofar": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "pensador": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "vida boa": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "virtude": ("Ciências Humanas e Sociais", "Filosofia e Ética"),
    "metafisica": ("Ciências Humanas e Sociais", "Filosofia e Ética"),

    # --- Psicologia ---
    "psicologia": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "psicologo": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "mente": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "comportamento": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "emocoes": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "terapia": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "autoconhecimento": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "psicanalise": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "subconsciente": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "psicoterapia": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "freud": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "jung": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "personalidade": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "inconsciente": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "pessoal": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "analise comportamental": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "inteligencia emocional": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "psicologia infantil": ('Ciências Biológicas e Saúde', 'Psicologia'),
    "neuropsicologia": ('Ciências Biológicas e Saúde', 'Psicologia'),

    # --- Sociologia e Política ---
    "sociologia": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "sociedade": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "politica": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "antropologia": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "cultura": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "governo": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "estado": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "democracia": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "direitos": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "movimentos sociais": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "relacoes humanas": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "grupos sociais": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "cidadania": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "justica social": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "ciencias politicas": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "geopolitica": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "relacoes internacionais": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "diversidade": ("Ciências Humanas e Sociais", "Sociologia e Política"),
    "curso direito": ("Ciências Humanas e Sociais", "Direito"),
    "faculdade direito": ("Ciências Humanas e Sociais", "Direito"),
    "delegado": ("Ciências Humanas e Sociais", "Direito"),
    "investigacao": ("Ciências Humanas e Sociais", "Direito"),
    "policial": ("Ciências Humanas e Sociais", "Direito"),
    "crimes": ("Ciências Humanas e Sociais", "Direito"),
    "constituicao": ("Ciências Humanas e Sociais", "Direito"),
    "direitos humanos": ("Ciências Humanas e Sociais", "Direito"),
    "debates juridicos": ("Ciências Humanas e Sociais", "Direito"),
    "estagiar direito": ("Ciências Humanas e Sociais", "Direito"),
    "law and order": ("Ciências Humanas e Sociais", "Direito"),
    "defensor publico": ("Ciências Humanas e Sociais", "Direito"),
    "juri": ("Ciências Humanas e Sociais", "Direito"),
    "tribunal do juri": ("Ciências Humanas e Sociais", "Direito"),
    # --- Direito ---
    "direito": ("Ciências Humanas e Sociais", "Direito"),
    "advocacia": ("Ciências Humanas e Sociais", "Direito"),
    "advogado": ("Ciências Humanas e Sociais", "Direito"),
    "leis": ("Ciências Humanas e Sociais", "Direito"),
    "legislacao": ("Ciências Humanas e Sociais", "Direito"),
    "juridico": ("Ciências Humanas e Sociais", "Direito"),
    "justica": ("Ciências Humanas e Sociais", "Direito"),
    "direito civil": ("Ciências Humanas e Sociais", "Direito"),
    "direito penal": ("Ciências Humanas e Sociais", "Direito"),
    "direito trabalhista": ("Ciências Humanas e Sociais", "Direito"),
    "direito empresarial": ("Ciências Humanas e Sociais", "Direito"),
    "direito constitucional": ("Ciências Humanas e Sociais", "Direito"),
    "direito internacional": ("Ciências Humanas e Sociais", "Direito"),
    "tribunal": ("Ciências Humanas e Sociais", "Direito"),
    "juiz": ("Ciências Humanas e Sociais", "Direito"),
    "promotor": ("Ciências Humanas e Sociais", "Direito"),
    "contratos": ("Ciências Humanas e Sociais", "Direito"),
    "direitos e deveres": ("Ciências Humanas e Sociais", "Direito"),
    "concurso publico": ("Ciências Humanas e Sociais", "Direito"),
    "oab": ("Ciências Humanas e Sociais", "Direito"),

    # =========================================
    # 9. NEGÓCIOS E EMPREENDEDORISMO
    # =========================================
    "empreender": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "shark tank": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "dragons den": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "rico": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "ficar rico": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "ganhar dinheiro": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "renda extra": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "vender": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "shopee": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "mercado livre": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "aliexpress": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "dropshipping": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "afiliados": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "monetizar": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "autonomo": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "freelancer": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "empreendedorismo": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "startup": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "criar empresa": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "negocio proprio": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "empreendedor": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "plano de negocios": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "abrir empresa": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "modelo de negocio": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "inovacao": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "vendas": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "mercado": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "cliente": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "loja online": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "e-commerce": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "mei": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "proprietario": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "proprio chefe": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "comercio": ("Negócios e Empreendedorismo", "Empreendedorismo"),
    "microempreendedor": ("Negócios e Empreendedorismo", "Empreendedorismo"),

    # --- Administração ---
    "administracao": ("Negócios e Empreendedorismo", "Administração"),
    "gestao": ("Negócios e Empreendedorismo", "Administração"),
    "administrar": ("Negócios e Empreendedorismo", "Administração"),
    "gestao empresarial": ("Negócios e Empreendedorismo", "Administração"),
    "gerenciamento": ("Negócios e Empreendedorismo", "Administração"),
    "liderar equipe": ("Negócios e Empreendedorismo", "Administração"),
    "recursos humanos": ("Negócios e Empreendedorismo", "Administração"),
    "gestao de pessoas": ("Negócios e Empreendedorismo", "Administração"),
    "coordenar": ("Negócios e Empreendedorismo", "Administração"),
    "organizar": ("Negócios e Empreendedorismo", "Administração"),
    "logistica": ("Negócios e Empreendedorismo", "Administração"),
    "processos": ("Negócios e Empreendedorismo", "Administração"),
    "produtividade": ("Negócios e Empreendedorismo", "Administração"),
    "eficiencia": ("Negócios e Empreendedorismo", "Administração"),
    "planejamento estrategico": ("Negócios e Empreendedorismo", "Administração"),
    "gerente": ("Negócios e Empreendedorismo", "Administração"),
    "gestao de projetos": ("Negócios e Empreendedorismo", "Administração"),
    "gestao de negocios": ("Negócios e Empreendedorismo", "Administração"),
    "tomada de decisao": ("Negócios e Empreendedorismo", "Administração"),

    # --- Finanças ---
    "financas": ("Negócios e Empreendedorismo", "Finanças"),
    "dinheiro": ("Negócios e Empreendedorismo", "Finanças"),
    "investimento": ("Negócios e Empreendedorismo", "Finanças"),
    "investir": ("Negócios e Empreendedorismo", "Finanças"),
    "bolsa de valores": ("Negócios e Empreendedorismo", "Finanças"),
    "acoes": ("Negócios e Empreendedorismo", "Finanças"),
    "mercado financeiro": ("Negócios e Empreendedorismo", "Finanças"),
    "contabilidade": ("Negócios e Empreendedorismo", "Finanças"),
    "contador": ("Negócios e Empreendedorismo", "Finanças"),
    "educacao financeira": ("Negócios e Empreendedorismo", "Finanças"),
    "financas pessoais": ("Negócios e Empreendedorismo", "Finanças"),
    "poupanca": ("Negócios e Empreendedorismo", "Finanças"),
    "controle financeiro": ("Negócios e Empreendedorismo", "Finanças"),
    "orcamento": ("Negócios e Empreendedorismo", "Finanças"),
    "analise financeira": ("Negócios e Empreendedorismo", "Finanças"),
    "planejamento financeiro": ("Negócios e Empreendedorismo", "Finanças"),
    "rendimentos": ("Negócios e Empreendedorismo", "Finanças"),
    "economia": ("Negócios e Empreendedorismo", "Finanças"),
    "criptomoedas": ("Negócios e Empreendedorismo", "Finanças"),
    "bitcoin": ("Negócios e Empreendedorismo", "Finanças"),
    "renda fixa": ("Negócios e Empreendedorismo", "Finanças"),
    "fundo imobiliario": ("Negócios e Empreendedorismo", "Finanças"),

    # --- Marketing e Comunicação ---
    "marketing": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "publicidade": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "propaganda": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "redes sociais": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "midia social": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "branding": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "gestao de marca": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "campanhas": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "anuncios": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "estrategia de marketing": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "seo": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "google ads": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "facebook ads": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "influencer": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "marketing digital": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "social media": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "comunicacao empresarial": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "gestao de campanhas": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "promocao": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "divulgacao": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),
    "pesquisa de mercado": ("Negócios e Empreendedorismo", "Marketing e Comunicação"),

    # =========================================
    # 10. COMUNICAÇÃO PROFISSIONAL
    # =========================================
    # --- Jornalismo ---
    "jornalismo": ("Comunicação Profissional", "Jornalismo"),
    "noticias": ("Comunicação Profissional", "Jornalismo"),
    "reporter": ("Comunicação Profissional", "Jornalismo"),
    "reportagem": ("Comunicação Profissional", "Jornalismo"),
    "entrevista": ("Comunicação Profissional", "Jornalismo"),
    "midia": ("Comunicação Profissional", "Jornalismo"),
    "jornal": ("Comunicação Profissional", "Jornalismo"),
    "revista": ("Comunicação Profissional", "Jornalismo"),
    "redacao jornalistica": ("Comunicação Profissional", "Jornalismo"),
    "comunicacao social": ("Comunicação Profissional", "Jornalismo"),
    "telejornalismo": ("Comunicação Profissional", "Jornalismo"),
    "radiojornalismo": ("Comunicação Profissional", "Jornalismo"),
    "podcast": ("Comunicação Profissional", "Jornalismo"),
    "cobertura de eventos": ("Comunicação Profissional", "Jornalismo"),
    "relato de fatos": ("Comunicação Profissional", "Jornalismo"),
    "portal de noticias": ("Comunicação Profissional", "Jornalismo"),
    "jornalista": ("Comunicação Profissional", "Jornalismo"),
    "apresentador": ("Comunicação Profissional", "Jornalismo"),
    "editorial": ("Comunicação Profissional", "Jornalismo"),

    # --- Oratória ---
    "oratoria": ("Comunicação Profissional", "Oratória"),
    "falar em publico": ("Comunicação Profissional", "Oratória"),
    "comunicacao": ("Comunicação Profissional", "Oratória"),
    "debate": ("Comunicação Profissional", "Oratória"),
    "argumentacao": ("Comunicação Profissional", "Oratória"),
    "discurso": ("Comunicação Profissional", "Oratória"),
    "apresentacao": ("Comunicação Profissional", "Oratória"),
    "palestra": ("Comunicação Profissional", "Oratória"),
    "comunicacao interpessoal": ("Comunicação Profissional", "Oratória"),
    "expressao": ("Comunicação Profissional", "Oratória"),
    "persuasao": ("Comunicação Profissional", "Oratória"),
    "eloquencia": ("Comunicação Profissional", "Oratória"),
    "diccao": ("Comunicação Profissional", "Oratória"),
    "conversacao": ("Comunicação Profissional", "Oratória"),
    "storytelling": ("Comunicação Profissional", "Oratória"),
    "contar historias": ("Comunicação Profissional", "Oratória"),
    "lideranca": ("Comunicação Profissional", "Oratória"),
    "mediar conversas": ("Comunicação Profissional", "Oratória"),
    "habilidades sociais": ("Comunicação Profissional", "Oratória"),
    "comunicacao eficaz": ("Comunicação Profissional", "Oratória"),
    "convencer pessoas": ("Comunicação Profissional", "Oratória"),
    "apresentar ideias": ("Comunicação Profissional", "Oratória"),
    "comunicador": ("Comunicação Profissional", "Oratória"),
    "ciencia dados": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "analise dados": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),

    "circuitos": ("Tecnologia e Computação", "Computação/Robótica"),
    "montar pc gamer": ("Tecnologia e Computação", "Computação/Robótica"),
    "upgrade pc": ("Tecnologia e Computação", "Computação/Robótica"),
    "pc master race": ("Tecnologia e Computação", "Computação/Robótica"),
    "hardware gamer": ("Tecnologia e Computação", "Computação/Robótica"),
    "overclock": ("Tecnologia e Computação", "Computação/Robótica"),
    "water cooling": ("Tecnologia e Computação", "Computação/Robótica"),
    "arduino": ("Tecnologia e Computação", "Computação/Robótica"),
    "raspberry pi": ("Tecnologia e Computação", "Computação/Robótica"),
    "placa video": ("Tecnologia e Computação", "Computação/Robótica"),
    "placa mae": ("Tecnologia e Computação", "Computação/Robótica"),
    "embarcados": ("Tecnologia e Computação", "Computação/Robótica"),
    "microcontroladores": ("Tecnologia e Computação", "Computação/Robótica"),
    "esp32": ("Tecnologia e Computação", "Computação/Robótica"),
    "consertar eletronicos": ("Tecnologia e Computação", "Computação/Robótica"),
    "manutencao computadores": ("Tecnologia e Computação", "Computação/Robótica"),
    "tecnico informatica": ("Tecnologia e Computação", "Computação/Robótica"),
    "engenharia eletronica": ("Tecnologia e Computação", "Computação/Robótica"),
    "trabalhar eletronica": ("Tecnologia e Computação", "Computação/Robótica"),
    "robos": ("Tecnologia e Computação", "Computação/Robótica"),
    "drones": ("Tecnologia e Computação", "Computação/Robótica"),
    "fpv drone": ("Tecnologia e Computação", "Computação/Robótica"),
    "corrida drones": ("Tecnologia e Computação", "Computação/Robótica"),
    "construir drone": ("Tecnologia e Computação", "Computação/Robótica"),
    "engenharia mecatronica": ("Tecnologia e Computação", "Computação/Robótica"),
    "braco robotico": ("Tecnologia e Computação", "Computação/Robótica"),
    "seguidor linha": ("Tecnologia e Computação", "Computação/Robótica"),
    "olimpiada robotica": ("Tecnologia e Computação", "Computação/Robótica"),
    "lego ev3": ("Tecnologia e Computação", "Computação/Robótica"),
    "first lego league": ("Tecnologia e Computação", "Computação/Robótica"),
    "obr": ("Tecnologia e Computação", "Computação/Robótica"),
    "trabalhar robotica": ("Tecnologia e Computação", "Computação/Robótica"),
    "carreira robotica": ("Tecnologia e Computação", "Computação/Robótica"),

    "programar": ("Tecnologia e Computação", "Programação e Software"),
    "programacao computador": ("Tecnologia e Computação", "Programação e Software"),
    "fazer programas": ("Tecnologia e Computação", "Programação e Software"),
    "c++": ("Tecnologia e Computação", "Programação e Software"),
    "ruby": ("Tecnologia e Computação", "Programação e Software"),
    "mods minecraft": ("Tecnologia e Computação", "Programação e Software"),
    "criar mods": ("Tecnologia e Computação", "Programação e Software"),
    "modpack": ("Tecnologia e Computação", "Programação e Software"),
    "programar plugins": ("Tecnologia e Computação", "Programação e Software"),
    "fazer bots discord": ("Tecnologia e Computação", "Programação e Software"),
    "bots": ("Tecnologia e Computação", "Programação e Software"),
    "scripts roblox": ("Tecnologia e Computação", "Programação e Software"),
    "lua": ("Tecnologia e Computação", "Programação e Software"),
    "programar roblox": ("Tecnologia e Computação", "Programação e Software"),
    "engenheiro software": ("Tecnologia e Computação", "Programação e Software"),
    "ciencia computacao": ("Tecnologia e Computação", "Programação e Software"),
    "criar sites": ("Tecnologia e Computação", "Programação e Software"),
    "criar aplicativos": ("Tecnologia e Computação", "Programação e Software"),
    "web": ("Tecnologia e Computação", "Programação e Software"),
    "fullstack": ("Tecnologia e Computação", "Programação e Software"),
    "banco dados": ("Tecnologia e Computação", "Programação e Software"),
    "faculdade computacao": ("Tecnologia e Computação", "Programação e Software"),
    "curso programacao": ("Tecnologia e Computação", "Programação e Software"),
    "ia": ("Tecnologia e Computação", "Programação e Software"),
    "aprendizado maquina": ("Tecnologia e Computação", "Programação e Software"),
    "deep learning": ("Tecnologia e Computação", "Programação e Software"),
    "chatgpt": ("Tecnologia e Computação", "Programação e Software"),
    "usar chatgpt": ("Tecnologia e Computação", "Programação e Software"),
    "gerar imagens ia": ("Tecnologia e Computação", "Programação e Software"),
    "midjourney": ("Tecnologia e Computação", "Programação e Software"),
    "dall-e": ("Tecnologia e Computação", "Programação e Software"),
    "stable diffusion": ("Tecnologia e Computação", "Programação e Software"),
    "criar com ia": ("Tecnologia e Computação", "Programação e Software"),
    "assistente virtual": ("Tecnologia e Computação", "Programação e Software"),
    "redes neurais": ("Tecnologia e Computação", "Programação e Software"),
    "processamento linguagem natural": ("Tecnologia e Computação", "Programação e Software"),
    "nlp": ("Tecnologia e Computação", "Programação e Software"),
    "visao computacional": ("Tecnologia e Computação", "Programação e Software"),
    "trabalhar com ia": ("Tecnologia e Computação", "Programação e Software"),
    "criar modelos ia": ("Tecnologia e Computação", "Programação e Software"),
    "pytorch": ("Tecnologia e Computação", "Programação e Software"),
    "tensorflow": ("Tecnologia e Computação", "Programação e Software"),
    "kaggle": ("Tecnologia e Computação", "Programação e Software"),
    "programar arduino": ("Tecnologia e Computação", "Programação e Software"),
    "programar robos": ("Tecnologia e Computação", "Programação e Software"),
    "carros autonomos": ("Tecnologia e Computação", "Programação e Software"),

    "big data": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),

    "data science": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "visualizacao dados": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "cientista dados": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "calculos": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "resolver equacoes": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "professor matematica": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "gostar matematica": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "bom matematica": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "problemas matematicos": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "rubik": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "logica matematica": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "numeros": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "matematica aplicada": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "trabalhar com numeros": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "carreira matematica": ("Ciências Exatas", "Matemática Aplicada e Análise de Dados"),
    "mecanica classica": ("Ciências Exatas", "Física"),
    "cinematica": ("Ciências Exatas", "Física"),
    "dinamica": ("Ciências Exatas", "Física"),
    "leis newton": ("Ciências Exatas", "Física"),
    "magnetismo": ("Ciências Exatas", "Física"),

    "fisica nuclear": ("Ciências Exatas", "Física"),
    "relatividade einstein": ("Ciências Exatas", "Física"),
    "professor fisica": ("Ciências Exatas", "Física"),
    "gostar fisica": ("Ciências Exatas", "Física"),
    "experimentos fisica": ("Ciências Exatas", "Física"),
    "fisica teorica": ("Ciências Exatas", "Física"),
    "olimpiada fisica": ("Ciências Exatas", "Física"),
    "obf": ("Ciências Exatas", "Física"),
    "carreira fisica": ("Ciências Exatas", "Física"),

    "fotografar ceu": ("Ciências Exatas", "Física"),
    "fotografia ceu noturno": ("Ciências Exatas", "Física"),
    "astrofotografia": ("Ciências Exatas", "Física"),
    "spacex": ("Ciências Exatas", "Física"),
    "engenharia aeroespacial": ("Ciências Exatas", "Física"),
    "agencias espaciais": ("Ciências Exatas", "Física"),
    "kerbal space program": ("Ciências Exatas", "Física"),
    "star citizen": ("Ciências Exatas", "Física"),
    "elite dangerous": ("Ciências Exatas", "Física"),
    "engenheiro aeroespacial": ("Ciências Exatas", "Física"),
    "trabalhar agencia espacial": ("Ciências Exatas", "Física"),
    "astronauta": ("Ciências Exatas", "Física"),
    "buracos negros": ("Ciências Exatas", "Física"),

    "compostos quimicos": ("Ciências Exatas", "Química"),
    "acidos bases": ("Ciências Exatas", "Química"),
    "ph": ("Ciências Exatas", "Química"),
    "laboratorio quimica": ("Ciências Exatas", "Química"),
    "fazer slime": ("Ciências Exatas", "Química"),
    "vulcao bicarbonato": ("Ciências Exatas", "Química"),
    "cristais": ("Ciências Exatas", "Química"),
    "professor quimica": ("Ciências Exatas", "Química"),
    "gostar quimica": ("Ciências Exatas", "Química"),
    "bioquimica": ("Ciências Exatas", "Química"),
    "farmaceutica": ("Ciências Exatas", "Química"),
    "quimico": ("Ciências Exatas", "Química"),
    "engenharia quimica": ("Ciências Exatas", "Química"),
    "quimica industrial": ("Ciências Exatas", "Química"),
    "industria quimica": ("Ciências Exatas", "Química"),
    "olimpiada quimica": ("Ciências Exatas", "Química"),
    "obq": ("Ciências Exatas", "Química"),

    "carreira quimica": ("Ciências Exatas", "Química"),

    "engenheiro": ("Ciências Exatas", "Engenharia"),

    "engenheiro civil": ("Ciências Exatas", "Engenharia"),
    "engenheiro mecanico": ("Ciências Exatas", "Engenharia"),
    "engenharia producao": ("Ciências Exatas", "Engenharia"),
    "engenharia naval": ("Ciências Exatas", "Engenharia"),
    "engenharia minas": ("Ciências Exatas", "Engenharia"),
    "construcao civil": ("Ciências Exatas", "Engenharia"),
    "projetos engenharia": ("Ciências Exatas", "Engenharia"),
    "construir no minecraft": ("Ciências Exatas", "Engenharia"),
    "circuitos redstone": ("Ciências Exatas", "Engenharia"),
    "automacao minecraft": ("Ciências Exatas", "Engenharia"),
    "cities skylines": ("Ciências Exatas", "Engenharia"),
    "simcity": ("Ciências Exatas", "Engenharia"),
    "plane crazy roblox": ("Ciências Exatas", "Engenharia"),
    "factorio": ("Ciências Exatas", "Engenharia"),
    "engenharia automotiva": ("Ciências Exatas", "Engenharia"),
    "crea": ("Ciências Exatas", "Engenharia"),
    "trabalhar construcao": ("Ciências Exatas", "Engenharia"),
    "trabalhar projetos": ("Ciências Exatas", "Engenharia"),
    "destacar engenheiro": ("Ciências Exatas", "Engenharia"),
}
import pandas as pd
import re


# Função para extrair o dicionário do texto do arquivo
def extract_dict_from_text(text):
    # Encontra a definição do dicionário no texto
    pattern = r'INTEREST_MAPPINGS\s*=\s*\{(.+?)\}'
    match = re.search(pattern, text, re.DOTALL)

    if not match:
        raise ValueError("Não foi possível encontrar a definição do dicionário no texto")

    # Transforma a string do dicionário em código Python executável
    dict_text = "{" + match.group(1) + "}"

    # Substitui caracteres que podem causar problemas
    dict_text = dict_text.replace('"', '\\"')  # Escapa aspas duplas

    # Define um dicionário vazio para armazenar o resultado
    result = {}

    # Itera por cada linha que parece uma definição de item de dicionário
    for line in dict_text.split('\n'):
        line = line.strip()
        if ':' in line and line.startswith('"'):
            # Extrai a chave e o valor
            key_value = line.split(':', 1)
            if len(key_value) == 2:
                key = key_value[0].strip().strip('"').strip("'")
                value_text = key_value[1].strip().rstrip(',')

                # Procura por um padrão de tupla como ("Categoria", "Subcategoria")
                tuple_match = re.search(r'\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)', value_text)
                if tuple_match:
                    main_category = tuple_match.group(1)
                    subcategory = tuple_match.group(2)
                    result[key] = (main_category, subcategory)

    return result


# Converte o dicionário para DataFrame
def convert_to_dataframe(interest_dict):
    data = []
    for term, categories in interest_dict.items():
        main_category, subcategory = categories
        data.append({
            'termo': term,
            'categoria_principal': main_category,
            'subcategoria': subcategory
        })
    return pd.DataFrame(data)


# Extrair o dicionário
interest_dict = INTEREST_MAPPINGS

# Converter para DataFrame
df = convert_to_dataframe(interest_dict)

# Mostrar informações sobre o dataset
print(f"Dataset criado com {len(df)} registros.")
print("\nDistribuição de categorias principais:")
print(df['categoria_principal'].value_counts())

print("\nDistribuição de subcategorias:")
print(df['subcategoria'].value_counts().head(10))  # Mostra apenas as 10 primeiras

# Salvar em diferentes formatos
df.to_csv('interest_mappings.csv', index=False)
df.to_json('interest_mappings.json', orient='records', force_ascii=False, indent=2)

print("\nArquivos 'interest_mappings.csv' e 'interest_mappings.json' criados com sucesso!")